uurloon = int(input('wat verdien je per uur? :' ))
print(uurloon)
aantaluur = int(input('Hoeveel uur heb je gewerkt? :' ))
print(aantaluur)
salaris = (str(aantaluur) + ' uur werken levert $' + str(aantaluur * uurloon) + ' op.')
print(salaris)